apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
    component: {{ include "app.fullname" . }}-service
  name: {{ include "app.fullname" . }}-service
spec:
  ports:
  - name: http-main
    port: 8080
    targetPort: http-main
  selector:
    {{- include "app.matchLabels" . | indent 4 }}